[workspace]
authors = ["Cameron Riddell <cameron@dutc.io>"]
channels = ["conda-forge"]
name = "2025-12-04_UsingMarimoforReproducibleNotebooks"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
polars = ">=1.35.2,<2"
marimo = ">=0.18.1,<0.19"
jupyterlab = ">=4.5.0,<5"
matplotlib = ">=3.10.8,<4"
